GET http://localhost:3001/parks


###

GET http://localhost:3001/parks/wrst


###

POST http://localhost:3001/parks
Content-Type: application/json

{
    "name": "Dry Tortugas",
    "fullName": "Dry Tortugas National Park",
    "parkCode": "drto",
    "description": "Almost 70 miles (113 km) west of Key West lies the remote Dry Tortugas National Park. This 100-square mile park is mostly open water with seven small islands. Accessible only by boat or seaplane, the park is known the world over as the home of magnificent Fort Jefferson, picturesque blue waters, superlative coral reefs and marine life, and the vast assortment of bird life that frequents the area."
}


###

PATCH http://localhost:3001/parks/maca
Content-Type: application/json

{
    "description": "Mammoth Cave National Park is home to thousands of years of human history and a rich diversity of plant and animal life, earning it the title of UNESCO World Heritage Site and International Biosphere Reserve. Enjoy the rolling hills, deep river valleys, and the world's longest known cave system."
}


### 

DELETE http://localhost:3001/parks/grca





### 

GET http://localhost:3001/images


###
GET http://localhost:3001/images/660360875e5c49e264622cea


### 

POST http://localhost:3001/images
Content-Type: application/json

{
    "id": 12,
    "parkCode": "gaar",
    "image": "https://www.nps.gov/common/uploads/structured_data/3C7A8B6B-1DD8-B71B-0B8B89FE0C6B6F4F.jpg"
}


###
 
PATCH http://localhost:3001/images/660363cb5d139f916f236c90
Content-Type: application/json

{
    "parkCode": "bisc",
    "image": "https://www.nps.gov/common/uploads/structured_data/3C870533-1DD8-B71B-0B70CFF5EF6538F1.jpg"
}


### 

DELETE http://localhost:3001/images/660363905d139f916f236c8d